version: '3'

services:
  account_backend:
    image: justinshagerty/account_backend:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_HOST: ${DB_HOST:?}
      DB_PORT: ${DB_PORT:?}
      DB_USERNAME: ${DB_USERNAME:?}
      DB_PASSWORD: ${DB_PASSWORD:?}
      DB_NAME: ${DB_NAME:?}
